global:
  scrape_interval:     5s   # How often to scrape targets
  evaluation_interval: 5s   # How often to evaluate rules

scrape_configs:
  - job_name: 'prom-grafana-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    # Labels added to every time series scraped from this target
    relabel_configs:
      - target_label: instance
        replacement: prom-grafana-app
